#!/usr/bin/env bash

prep_day=$(cat complete|cut -d' ' -f3)

start(){
  IFS='%' #preserve whitespaces
  url="https://takeuforward.org/interviews/strivers-sde-sheet-top-coding-interview-problems/"
  curl -s $url | pup 'details' | sed 's/<a href=//g;s/\/">//g;s/Day \([0-9]\+\)/\n[ Day \1 ]/g;s/https/\t\thttps/g;s/: //g;/Link\|YT$\|Find\|Problem\|Video/d' |cut -d'"' -f2| grep -v '<*>\|     \/' > todo
  printf "Challenge started ...\n\n"
  printf "[ Day 1 ] : $(date)\n\n" | tee complete
  day 1 | tail -n +3
}

day(){
  if [ "$1" != "30" ];then
    sed -n "/\[ Day $1 ]/, /\[ Day $(($1+1)) ]/p" todo | head -n -2
  else
    sed -n "/\[ Day $1 ]/, /\[ Day $(($1+1)) ]/p" todo
  fi
}

did(){
  day $prep_day
  read -p "Enter links count('a' for day complete) : " count
}

for arg in $@
do
  printf "\n"
  case "$1" in
    -p|--progress)
      bat complete
      ;;
    -h|--help)
      echo "prep -h            : this screen"
      echo "prep start         : start the challenge "
      echo "prep day 1         : shows things todo in day 1"
      echo "prep did 3         : adds checked in front of next 3 links in running day"
      echo "prep -p/--progress : progress in the challenge"
      echo "prep -d/--day      : shows which day in the challenge"
      ;;
    -d|--day)
      echo "Day : $prep_day"
      ;;
    -*)
      printf "Invalid argument !!\ncheck 'prep -h'\n"
      ;;
  esac
  if [[ $arg == "day" || $arg  == "start" || $arg == "did" ]];then
    $@
  fi
done

